---
- name: Deploy App
  hosts: all
  user: ec2-user
  gather_facts: false
  become: yes

  vars:
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
    ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false

  pre_tasks:
    - name: Wait for connection to become reachable
      wait_for_connection:

    - name: Ensure Python is installed
      become: true
      raw: test -e /usr/bin/python3 || (yum -y update && yum install -y python3)
      changed_when: false

  roles:
    - configure-server
    - deployment
